# Generated by Django 5.0.6 on 2024-08-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
