# Generated by Django 5.0.6 on 2024-09-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_user_payment_where_ride_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='where_ride_from',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='where_ride_to',
        ),
    ]
