# Generated by Django 5.0.6 on 2024-09-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
