# Generated by Django 5.0.6 on 2024-09-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_rename_user_payment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='username',
            new_name='user',
        ),
    ]
