# Generated by Django 5.0.6 on 2024-09-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_payment_driver_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='driver_info',
        ),
    ]
