# Generated by Django 5.0.6 on 2024-09-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_payment_name_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
