# Generated by Django 5.0.6 on 2024-09-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_remove_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='driver_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
