# Generated by Django 5.0.6 on 2024-09-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_alter_payment_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='driver_name',
        ),
    ]
