# Generated by Django 5.0.6 on 2024-08-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
