# Generated by Django 5.0.6 on 2024-08-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_rename_user_driver_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='username',
            new_name='user',
        ),
    ]
