# Generated by Django 5.0.6 on 2024-08-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_driver_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Driver'},
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
