# Generated by Django 5.0.6 on 2024-08-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_alter_driver_options_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
