# Generated by Django 5.0.6 on 2024-08-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_driver_driving_licence_driver_number_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
