# Generated by Django 5.0.6 on 2024-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0014_driver_email_driver_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driving_licence',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=50),
        ),
    ]
