# Generated by Django 5.0.6 on 2024-08-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_alter_driver_driving_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
