# Generated by Django 5.0.6 on 2024-08-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0019_alter_driver_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='image',
        ),
    ]
