# Generated by Django 5.0.6 on 2024-08-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0020_remove_driver_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='where_ride_to_where_ride',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
