# Generated by Django 5.0.6 on 2024-08-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0021_driver_where_ride_to_where_ride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='where_ride_to_where_ride',
            new_name='where_ride_from',
        ),
        migrations.AddField(
            model_name='driver',
            name='where_ride_to',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
