# Generated by Django 5.0.6 on 2024-09-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0023_alter_driver_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_ride_from', models.CharField(max_length=255)),
                ('where_ride_to', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ride Completed', 'Ride Completed')], default='Pending', max_length=20)),
            ],
        ),
    ]
