# Generated by Django 5.0.6 on 2024-08-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'verbose_name_plural': 'Ride'},
        ),
    ]
