# Generated by Django 5.0.6 on 2024-08-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
    ]
