# Generated by Django 5.0.6 on 2024-08-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_remove_ride_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='rider',
        ),
        migrations.AddField(
            model_name='ride',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
