# Generated by Django 5.0.6 on 2024-08-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_ride_rider_ride_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='status',
        ),
    ]
