# Generated by Django 5.0.6 on 2024-09-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_orderhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
