# Generated by Django 5.0.6 on 2024-09-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_alter_ride_options_ride_created_by_alter_ride_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='created_by',
        ),
    ]
