# Generated by Django 5.0.6 on 2024-09-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_remove_ride_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riderequest',
            options={},
        ),
    ]
