# Generated by Django 5.0.6 on 2024-09-06 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_remove_riderequest_driver_remove_riderequest_ride_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='where_ride_from',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='where_ride_to',
        ),
        migrations.AddField(
            model_name='riderequest',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderequest',
            name='ride',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rides.ride'),
            preserve_default=False,
        ),
    ]
