# Generated by Django 5.0.6 on 2024-09-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0022_rename_where_ride_to_where_ride_driver_where_ride_from_and_more'),
        ('rides', '0018_riderequest_where_ride_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
    ]
