# Generated by Django 5.0.6 on 2024-09-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0022_ride_user_alter_riderequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
    ]
