# Generated by Django 5.0.6 on 2024-09-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0027_ride_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='driver',
        ),
    ]
