# Generated by Django 5.0.6 on 2024-09-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0023_alter_driver_options'),
        ('rides', '0031_rename_user_ride_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
    ]
