# Generated by Django 5.0.6 on 2024-09-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0033_rename_username_ride_driver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver',
            new_name='user',
        ),
    ]
