# Generated by Django 5.0.6 on 2024-09-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0023_alter_driver_options'),
        ('rides', '0046_alter_ride_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
    ]
