# Generated by Django 5.0.6 on 2024-09-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0047_alter_ride_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
    ]
