# Generated by Django 5.0.6 on 2024-09-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0023_alter_driver_options'),
        ('rides', '0048_remove_ride_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='driver_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
            preserve_default=False,
        ),
    ]
