# Generated by Django 5.0.6 on 2024-09-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0049_riderequest_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='driver_name',
        ),
    ]
