# Generated by Django 5.0.6 on 2024-09-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0054_alter_ride_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='driver',
        ),
    ]
