# Generated by Django 5.0.6 on 2024-10-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0057_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
