# Generated by Django 5.0.6 on 2024-08-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_review_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
