# Generated by Django 5.0.6 on 2024-09-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_review_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='driver',
        ),
    ]
