# Generated by Django 5.0.6 on 2024-09-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_review_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
